//added some features

pipeline{
	agent any
  
	stages{
    
		stage( 'clone' ){
		steps{
			git branch:'main' ,url:'https://github.com/likhithaal/Amazon_cicd.git'
		    }
  		}
      
		stage( 'clean' ){
		steps{
			sh 'cd Amazon && mvn clean'
			}
		}
		
		stage( 'test' ){
		steps{
			sh 'cd Amazon && mvn test'
			}
		}
		
		stage( 'build' ){
		steps{
			sh 'cd Amazon && mvn clean install'
			}
		}
		
	}
}
